### ISSUE TITLE
Necessary Start Screens for China patch

### ISSUE THREAD

**Issue by Zephyrum** [Zephyrum/FoI#38]
Majors - must have
Yuan (YUA)
Ming (MNG)
Yue (YUE)

Generic - must have
Chinese Superregion

Minors - not necessary
Moghulistan (MGL)
Qin (QIN)
Jin (JIN)
Min (MIN)

**Comment by Zephyrum** [comment]
**YUE**

The East is experience a phenomena it never saw itself experiencing: religious conflicts. The many teachers that build the philosophical apparatus of the great dynasties of China and it's many sattlelites were just that - philosophical. Faith has hardly concerned the peoples of the Middle Kingdom, for while there is plenty of variety in worship amongst regions, and different tales about mythical beings, never have those dictated much of a man's live beyond superstitiousness. But this is a thing of the past.

More proactive, universalist faiths have long been created in the far West, to lands the Middle Kingdom have identified as Daqin, where a civilization to match the Han has formed and thrived. These faiths have estabilished rites for all to follow and constantly enter conflict with different faiths or, sometimes, simply different sects. The arrival of one of those sects, the Nestorians, through the Hexi corridor, meant the creation of a theological landscape never before seen amongst the Han. The Mongol control of both the Middle Kingdom and the Silk Road meant that this spread was constatly accelerated, and for their harshness, the Yuan dynasty didn't particularly give much thought about intervening in the common citizen's beliefs.

Now, after a boom of a foreign faith with little to do with the Chinese, many a man could not find comfort in knowing their neighbors might be turned away from the great spirits in favor of a single "God", whose very existance is cryptic beyond belief. Thus, a cultural movement in the growingly rich delta of the Pearl river has seen the rise of a competing faith - four spirits that have long been worshipped as the central deities, and a set of rites tailored by the Han for the Han. Not many thought of it seriously at first, seeing it as some odd bastardization of faith. Had the landscape of the region been any different, this would have been curbed here.

But history often relies on the small things. The Yuan has been collapsing in the North, and the South is politically isolated from their masters (in name, at least) by a great warlord in Nanjing. this disconnect has given free rein for all of the Southern governors to do as they please, and the new faith - named the cult of the four symbols (Sixiang) - has found itself adopted by the governor of Guangdong. Having had ascendancy of both local pagans and Nestorians, the compromise was believed to be ideal for the young Yuehan Yue, who would become the main patron and one of the main scholars of the faith.

As the Yuan in Beijing dives head-first into a seemingly inevitable conflict with the Ming in Nanjing, the South has been described of seeing the meteoric rise of banditry and spread of the Sixiang faith. Standing right at the center of those changes, the rapidly growing Yue must prepare for the ever-expanding list of regional rivals' desire to put away the fires of their new religion, all the while keeping an eye out for the developments further North...

**Comment by Zephyrum** [comment]
**MING**

That old coot Adai Borjigin is closing in on his sixties. He gave us a lot of trouble already. Not one too grand at scheming and diplomacy, he is definetely not shabby at the art of war and has been quelling our attempts to rise by manipulating the Red Turbans by cutting them short. Regardless, if a spear isn't going to do it, age is certain to eventually defeat the mighty Khagan.

From our base in Jiangsu Province, we have been chipping away at the invasive Yuan for decades now, growing ourselves to a fine state in the center of the world's greatest empire. The Han people flock to us, seeking to end the Mongol rule once and for all. Our coordinated rebellions in the form of the Red Turbans have been giving us plenty room and time to boss around our weaker governor neighbors. And the authorities in Khanbaliq - nay, Beijing, as it was once called and soon will be again - have not been able to stop our advance. Until Adai, that is. But his son Taisun is showing the signs of weakness we are all too accostumed to abuse from the Yuan - inbreeding in an attempt to keep the "holiness" of their heavenly mandate (and possibly a lot of paranoia and fear of the courtesans growing too influent) being the most noticeable one.

This time, we'll be decisive. No more skirmishes, just all-out war. The Mandate of the Heavens has clearly abandoned the Borjigins, and it's time for the Zhu to rise. Deals with the Zhou clan of Nanjing has secured our court and granted us two quick-witted generals to lead our men in the fight for the freedom of the Han people. We control a larger tax base than the Yuan. So long as we can fight against their mighty horsemen, we have a surefire victory awaiting us.

As we bring forth the dusk of the yellow sky, the red one is to rise in it's place. And all it takes is a few more years, one disease, one fatality.

**Comment by Zephyrum** [comment]
MING - Non-narrative

Adai Borjigin is closing in on his sixties. He has given the rising Ming a lot of trouble already. Not one too grand at scheming and diplomacy, he mastery of the art of war has been quelling attempts from Qizhen Zhu to rise to prominence by manipulating the Red Turbans. Regardless, if a spear isn't going to do it, age is certain to eventually defeat the mighty Khagan.

From their base base in Jiangsu Province, the Zhu clan has been chipping away at the invasive Yuan for decades now, growing to a fine state in the center of the world's greatest empire. The Han people flock to them, seeking to end the Mongol rule once and for all. Coordinated rebellions in the form of the Red Turbans have been giving them a much necessary time to defeat weaker provincial governor neighbors. And the authorities in Khanbaliq - or Beijing, as it was once called and soon might be again - have not been able to stop the creeping Ming's advance. Until Adai, that is. But his son Taisun is showing the many signs the Zhus are all too accostumed to abuse from the Yuan - inbreeding in an attempt to keep the "holiness" of their heavenly mandate (and possibly a lot of paranoia and fear of the courtesans growing too influent) being the most noticeable one.

Yet this time, the winds flow differently, and there is a sense of urgency in the air. No more skirmishes - the Ming plans for all-out war, claiming the Mandate of the Heavens has clearly abandoned the Borjigins. Deals with the Zhou clan of Nanjing has secured their court standings and granted them two quick-witted generals to lead in the fight for the freedom of the Han people. Their tax base surpasses that of the Yuan. If they can counter against the mighty horsemen of the steppes, victory might seem inevitable.

As the dusk of the yellow sky approaches, the red one seems to rise in it's place. And all it takes is a few more years, one disease, one fatality.

**Comment by Zephyrum** [comment]
**YUAN**

In a week, Adai Borjigin will have reached the 55th year of his life. His small and ever-shrinking inner circle of loyalists knows well enough that this is quite the age, specially so for one of a warrior background, and expect the mighty Khagan to eventually fall ill to the one test no human has ever passed - time. The problem: those who stand against him are also well aware of it.

For decades, the Yuan has been slowly falling. Collapsing under it's own weight, it's territory too vast to ensure it's all in the hands of loyal, clean governors. Instead, disloyal and corrupt ones rise. Some build grand fortunes, some carve their own state that operates independently in all but name. The tale of the Mongol conquests is now an old one, too long gone to remember the fine details of. And the greatest of the states born out of that legacy is quickly tearing itself apart.

Adai has been the one Emperor that refused to let his legacy fade away. Confronting the warlords, building his loyalist circle, securing the help of other skilled men from his court in Khanbaliq. Yet he is too old to bear a new son, and his only heir suffers pressure from courtesans who want to "educate" him, attempted murders, signs of inbreeding and all-around frailness.

The rest of his small clique includes his wife (and cousin) Bayarma, the loyalist governor of Jin, Taoshui Cao, and his favored cavalry commander, Qi Bing. The four year old prince, Taisun, is the key to the succession, and, by extension, the one that will bring upon the Middle Kingdom the turning point - whether the Yuan decisively falls or turns around and defeats it's foes.

**Comment by Zephyrum** [comment]
**Generic Chinese**

China is whole again. And it broke again.

**Comment by The-Jerm** [comment]
The East is experience a phenomena it never saw itself experiencing: religious conflicts. The many teachers that build the philosophical apparatus of the great dynasties of §YChina§! and it's many satellites were just that - philosophical. Faith has hardly concerned the peoples of the §YMiddle Kingdom§!, for while there is plenty of variety in worship amongst regions, and different tales about mythical beings, never have those dictated much of a man's live beyond superstitiousness. But this is a thing of the past.\nMore proactive, universal faiths have long been created in the far West, to lands the §YMiddle Kingdom§! have identified as §YDaqin§!, where a civilization to match the §YHan§! has formed and thrived. These faiths have established rites for all to follow and constantly enter conflict with different faiths or, sometimes, simply different sects. The arrival of one of those sects, the §YNestorians§!, through the §YHexi Corridor§!, meant the creation of a theological landscape never before seen amongst the §YHan§!. The §YMongol§! control of both the §YMiddle Kingdom§! and the §YSilk Road§! meant that this spread was constantly accelerated, and for their harshness, the §YYuan§! dynasty didn't particularly give much thought about intervening in the common citizen's beliefs. \nNow, after a boom of a foreign faith with little to do with the §YChinese§!, many a man could not find comfort in knowing their neighbors might be turned away from the great spirits in favor of a single "§YGod§!", whose very existence is cryptic beyond belief. Thus, a cultural movement in the growingly rich delta of the §YPearl River§! has seen the rise of a competing faith - four spirits that have long been worshiped as the central deities, and a set of rites tailored by the §YHan§! for the §YHan§!. Not many thought of it seriously at first, seeing it as some odd bastardization of faith. Had the landscape of the region been any different, this would have been curbed here. \nBut history often relies on the small things. The §YYuan§! has been collapsing in the North, and the South is politically isolated from their masters (in name, at least) by a great warlord in §YNanjing§!. This disconnect has given free rein for all of the southern governors to do as they please, and the new faith - named the cult of the four symbols (§YSixiang§!) - has found itself adopted by the governor of §YGuangdong§!. Having had ascendancy of both local pagans and §YNestorians§!, the compromise was believed to be ideal for the young §YYuehan Yue§!, who would become the main patron and one of the main scholars of the faith. \nAs the §YYuan§! in §YBeijing§! dives head-first into a seemingly inevitable conflict with the §YMing§! in §YNanjing§!, the South has been described of seeing the meteoric rise of banditry and spread of the §YSixiang§! faith. Standing right at the center of those changes, the rapidly growing §YYue§! must prepare for the ever-expanding list of regional rivals' desire to put away the fires of their new religion, all the while keeping an eye out for the developments further North...

**Comment by The-Jerm** [comment]
§YAdai Borjigin§! is closing in on his sixties. He has given the rising §YMing§! a lot of trouble already. Not one too grand at scheming and diplomacy, he mastery of the art of war has been quelling attempts from §YQizhen Zhu§! to rise to prominence by manipulating the §YRed Turbans§!. Regardless, if a spear isn't going to do it, age is certain to eventually defeat the mighty §YKhagan§!. \nFrom their base base in §YJiangsu Province§!, the §YZhu§! clan has been chipping away at the invasive §YYuan§! for decades now, growing to a fine state in the center of the world's greatest empire. The §YHan§! people flock to them, seeking to end the §YMongol§! rule once and for all. Coordinated rebellions in the form of the §YRed Turbans§! have been giving them a much necessary time to defeat weaker provincial governor neighbors. And the authorities in §YKhanbaliq§! - or §YBeijing§!, as it was once called and soon might be again - have not been able to stop the creeping §YMing's§! advance. Until §YAdai§!, that is. But his son §YTaisun§! is showing the many signs the §YZhus§! are all too accustomed to abuse from the §YYuan§! - inbreeding in an attempt to keep the "holiness" of their heavenly mandate (and possibly a lot of paranoia and fear of the courtesans growing too influent) being the most noticeable one. \nYet this time, the winds flow differently, and there is a sense of urgency in the air. No more skirmishes - the §YMing§! plans for all-out war, claiming the §YMandate of the Heavens§! has clearly abandoned the §YBorjigins§!. Deals with the §YZhou§! clan of §YNanjing§! has secured their court standings and granted them two quick-witted generals to lead in the fight for the freedom of the §YHan§! people. Their tax base surpasses that of the §YYuan§!. If they can counter against the mighty horsemen of the steppes, victory might seem inevitable. \nAs the dusk of the yellow sky approaches, the red one seems to rise in it's place. And all it takes is a few more years, one disease, one fatality.

**Comment by The-Jerm** [comment]
In a week, §YAdai Borjigin§! will have reached the 55th year of his life. His small and ever-shrinking inner circle of loyalists knows well enough that this is quite the age, specially so for one of a warrior background, and expect the mighty §YKhagan§! to eventually fall ill to the one test no human has ever passed - time. The problem: those who stand against him are also well aware of it. \nFor decades, the §YYuan§! has been slowly falling. Collapsing under it's own weight, it's territory too vast to ensure it's all in the hands of loyal, clean governors. Instead, disloyal and corrupt ones rise. Some build grand fortunes, some carve their own state that operates independently in all but name. The tale of the §YMongol§! conquests is now an old one, too long gone to remember the fine details of. And the greatest of the states born out of that legacy is quickly tearing itself apart. \n§YAdai§! has been the one §YEmperor§! that refused to let his legacy fade away. Confronting the warlords, building his loyalist circle, securing the help of other skilled men from his court in §YKhanbaliq§!. Yet he is too old to bear a new son, and his only heir suffers pressure from courtesans who want to "educate" him, attempted murders, signs of inbreeding and all-around frailness. \nThe rest of his small clique includes his wife (and cousin) §YBayarma§!, the loyalist governor of §YJin§!, §YTaoshui Cao§!, and his favored cavalry commander, §YQi Bing§!. The four year old prince, §YTaisun§!, is the key to the succession, and, by extension, the one that will bring upon the §YMiddle Kingdom§! the turning point - whether the §YYuan§! decisively falls or turns around and defeats it's foes.

**Comment by The-Jerm** [comment]
It seems fate itself does not like to give the §YMiddle Kingdom§! - §YChina§! - a break. Ever since the early days of the §YHan§! people, it seems it's resting point is that of chaos, regional governors, and corrupt rulers. Great unifier after great unifier has come and gone, and yet it always seemed to collapse into multiple entities. Governors declare independence, barbarians invade, the region gets fractured. This time it's not different - the §YMongols§! of the §YYuan§! dynasty invaded and secured their place in history. And now, the very same §YMongols§! are fighting to keep what's left of their §YEmpire§! whole, as warlords stake their claims to their regions, if not the whole §YEmpire§!. \nWhat is new, though, in the insertion of many different faiths, coming from the West to seek to proselytize inside §YChinese§! borders. Many warlord's peasants have converted, some warlords followed suit, and the religion question seems to be moving towards being a major point of content in the upcoming warlord era. \nTo the North, the remains of the §YYuan§! are at the knife's edge, but still in control, with the loyalists of §YJin§! assisting them, and the §YQin§! taking the blunt of the religious drama. In the center, the §YZhu§! clan has secured their power base, one much greater than that of all the others, rivaling central authority, threatening the §YWu§! in §YJiangdong§!. The South is still full of smaller, pettier governors, the most notable one being the rising §YYue§!, having just engaged on converting to a new faith, as well as the §YMin§!, essentially ruled by a junta of military officers. \nThe sand castle might finally come crashing down as the §YKhagan§!, §YAdai§!, approaches his late years. Whether it is the court intrigue that is going to displace him, or an invasion from one of the rival warlords - or even if he is going to be displaced, to begin with - it's clear that stability is almost certainly not going to mark the next few decades.
