### ISSUE TITLE
Chindia Patch - Mission trees

### ISSUE THREAD

**Issue by Zephyrum** [Zephyrum/FoI#40]
**Large (>20 missions)**
Ming - Drafted, being developed by Cinnamon
Yue - Complete

**Medium (6 to 19 missions)**
Yuan - Drafted

**Small (<5 missions)**
Moghulistan/Chagatai - Complete
Min - Complete
Jin - Complete
Generic Chinese - Complete

**Comment by Zephyrum** [comment]
Updated the issue showing the status of each tree. Moved Qin and Jin to small since they are lesser importance trees and realistically none of us is that interested. I'll see if Thrawn and I can, at some point this week, catch up and do the three missing small ones, while Cinna continues Ming. Then we'll see how to handle the Yue/Yuan ones.

**Comment by Zephyrum** [comment]
Update part 2 electric boogaloo: Drafted Moghulatai and Jin ideas. Now the only undrafted set is Yuan.

**Comment by Zephyrum** [comment]
flavor_yue.2 still needs an effect

**Comment by neothiamin** [comment]
flavor_yue.2.a no longer needs an effect

**Comment by Zephyrum** [comment]
In which case we're done here and I'm leaving only the testing label

**Comment by Zephyrum** [comment]
Closing due to Couch's testing
