### ISSUE TITLE
Clean up Sixiang Events

### ISSUE THREAD

**Issue by neothiamin** [Zephyrum/FoI#43]
* Localization
* Modifiers that don't exist
* Adding MTTH

**Comment by Zephyrum** [comment]
Rather than MTTH, we'll use a pulse

What modifiers are missing? I'll fix them asap

**Comment by neothiamin** [comment]
"Sixiang_Syncretism". I'll fix it right now, don't worry.

As for the pulse, why? Why not MTTH?

**Comment by Zephyrum** [comment]
Because it's the standard for religious events like Orthodox and Catholic. Prevents the whole thing from being too spammy or not spammy enough.

**Comment by neothiamin** [comment]
That's fair.

**Comment by Zephyrum** [comment]
Best left for it's existing issue
